- name: install server and configure it
  hosts: all
  become: yes
  roles:
    - role: secondary_disk
      vars:
        device: /dev/sdb
        fs_type: xfs
        mount_path: /srv

    - role: fail2ban

    - role: geerlingguy.ntp
      vars:
        ntp_enabled: true
        ntp_timezone: Europe/Zurich
        ntp_area: 'ch'

    - role: geerlingguy.firewall
      vars:
        firewall_allowed_tcp_ports:
          - '22' # SSH
          - '9100' # node_exporter

    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker-compose
            state: latest
          - name: docker
            state: latest

    - role: geerlingguy.docker
      vars:
        docker_daemon_options:
          data-root: /srv/docker

    - role: deploy_ic_it_ssh_keys

    - role: geerlingguy.node_exporter
      vars:
        node_exporter_host: '0.0.0.0'
        node_exporter_port: 9100

    - role: jaepetto.ansible_mount_cifs_volume
      vars:
        cifs_volume: '//cdh1arch.epfl.ch/project_replica'
        mount_point: '/mnt/project_replica'
        creds_uuid: 'dhlabreplicacifspwd'
        fstab_options: 'user,uid=903034,gid=11703,file_mode=0640,dir_mode=0750,ro,suid,vers=3.0,credentials=/etc/{{ creds_uuid }}'
        username: "{{ lookup('ansible.builtin.env', 'PROJECT_REPLICA_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'PROJECT_REPLICA_PASSWORD') }}"
        domain: 'INTRANET'
